version: '3.8'

services:
  db:
    image: postgres:latest
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: postgres
    restart: always
    ports:
    - "5432:5432"